export default {
  TYPE_ITEM_SECTION_NO_TITLE : 0,//带边框无标题格子
  TYPE_ITEM_SECTION_HAS_TITLE : 1,//带标题格子(上方/下方)
  TYPE_ITEM_SECTION_PLACE_HOLDER : 3,//占位格子
  TYPE_ITEM_HISTORY_TEXT: 4,//历史格子-文字
  TYPE_ITEM_HISTORY_IMG: 5,//历史格子-图片
  TYPE_ITEM_SECTION_FOCUS_CHANGE_IMG : 6,//焦点变图格子
  TYPE_ITEM_SECTION_CELL_PLAYER:7,//小窗播放
  TYPE_ITEM_SECTION_CELL_PLAYER_LIST:8,//小窗列表播放
  TYPE_ITEM_SECTION_LOOP_IMG:9,//轮播图片格子
  TYPE_WATERFALL_SECTION_4K:101,//4K section
  TYPE_WATERFALL_SECTION_4K_ITEM:10,//4K item格子
  TYPE_WATERFALL_SECTION_SMALL_4K:102,//放映厅 小 4K section
  TYPE_WATERFALL_SECTION_SMALL_4K_ITEM:11,//放映厅 小 4K item格子
  TYPE_WATERFALL_SECTION_SHORT_SCREEN:103,//短视频全屏背景播放
  TYPE_WATERFALL_SECTION_SHORT_SCREEN_ITEM:12,//短视频 item格子
}
