export default {
  TYPE_ITEM_SECTION_FOCUS_CHANGE_IMG : 1,//焦点变图格子
  TYPE_ITEM_SECTION_NO_FRAME : 2,//无边框格子
  TYPE_ITEM_SECTION_PLACE_HOLDER : 3,//占位格子
  TYPE_ITEM_SECTION_CELL_PLAYER : 10008,//小窗播放格子类型
}
